#!/bin/bash
#----------AUTHOR------------
	# Jacob Salmela
	# 14 November 2012
	# https://github.com/jakesalmela/

#---------DESCRIPTION--------
	# Force emptys the trash as the currently logged in user
	# Commands must be properly escaped in order to run correctly

#----------VARIABLES---------
	currentuser=$(stat -f "%Su" /dev/console)

#----------FUNCTIONS---------
###########################
function runCommandAsUser()

	{	
	# Run command as user
	su -c "$currentUser" "$1"
	}

#----------------------------
#----------------------------
#-----------SCRIPT-----------
#----------------------------
runCommandAsUser <command_to_run>
